-- STUDIO — 04 claves foráneas e índices
-- 61 FKs (pg_constraint contype='f') + 78 índices que no respaldan constraints PK/UNIQUE (pg_indexes).
-- Nota: pos_cajas_usuario_id_fkey y profiles_id_fkey referencian auth.users(id), que ya existe en Supabase.

-- ---------------------------------------------------------------- FKs
alter table public.auditoria add constraint auditoria_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_abonos add constraint pos_abonos_caja_id_fkey FOREIGN KEY (caja_id) REFERENCES pos_cajas(id) ON DELETE SET NULL;
alter table public.pos_abonos add constraint pos_abonos_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES pos_clientes(id) ON DELETE CASCADE;
alter table public.pos_abonos add constraint pos_abonos_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_abonos add constraint pos_abonos_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES pos_ventas(id) ON DELETE SET NULL;
alter table public.pos_apartado_pagos add constraint pos_apartado_pagos_apartado_id_fkey FOREIGN KEY (apartado_id) REFERENCES pos_apartados(id) ON DELETE CASCADE;
alter table public.pos_apartados add constraint pos_apartados_serial_id_fkey FOREIGN KEY (serial_id) REFERENCES pos_seriales(id) ON DELETE RESTRICT;
alter table public.pos_asiento_lineas add constraint pos_asiento_lineas_asiento_id_fkey FOREIGN KEY (asiento_id) REFERENCES pos_asientos(id) ON DELETE CASCADE;
alter table public.pos_banco_conciliaciones add constraint pos_banco_conciliaciones_cuenta_bancaria_id_fkey FOREIGN KEY (cuenta_bancaria_id) REFERENCES pos_cuentas_bancarias(id) ON DELETE RESTRICT;
alter table public.pos_banco_conciliaciones add constraint pos_banco_conciliaciones_extracto_id_fkey FOREIGN KEY (extracto_id) REFERENCES pos_banco_extractos(id) ON DELETE CASCADE;
alter table public.pos_banco_conciliaciones add constraint pos_banco_conciliaciones_movimiento_id_fkey FOREIGN KEY (movimiento_id) REFERENCES pos_banco_movimientos(id) ON DELETE CASCADE;
alter table public.pos_banco_extractos add constraint pos_banco_extractos_cuenta_bancaria_id_fkey FOREIGN KEY (cuenta_bancaria_id) REFERENCES pos_cuentas_bancarias(id) ON DELETE RESTRICT;
alter table public.pos_banco_movimientos add constraint pos_banco_movimientos_cuenta_bancaria_id_fkey FOREIGN KEY (cuenta_bancaria_id) REFERENCES pos_cuentas_bancarias(id) ON DELETE RESTRICT;
alter table public.pos_caja_movimientos add constraint pos_caja_movimientos_caja_id_fkey FOREIGN KEY (caja_id) REFERENCES pos_cajas(id) ON DELETE CASCADE;
alter table public.pos_caja_movimientos add constraint pos_caja_movimientos_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_cajas add constraint pos_cajas_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_cajas add constraint pos_cajas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.pos_categorias add constraint pos_categorias_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_clientes add constraint pos_clientes_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_compra_items add constraint pos_compra_items_compra_id_fkey FOREIGN KEY (compra_id) REFERENCES pos_compras(id) ON DELETE CASCADE;
alter table public.pos_compra_items add constraint pos_compra_items_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_compra_pagos add constraint pos_compra_pagos_compra_id_fkey FOREIGN KEY (compra_id) REFERENCES pos_compras(id) ON DELETE SET NULL;
alter table public.pos_compra_pagos add constraint pos_compra_pagos_cuenta_bancaria_id_fkey FOREIGN KEY (cuenta_bancaria_id) REFERENCES pos_cuentas_bancarias(id) ON DELETE RESTRICT;
alter table public.pos_compra_pagos add constraint pos_compra_pagos_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_compras add constraint pos_compras_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_config add constraint pos_config_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_cotizacion_items add constraint pos_cotizacion_items_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES pos_cotizaciones(id) ON DELETE CASCADE;
alter table public.pos_credito_eventos add constraint pos_credito_eventos_financiamiento_id_fkey FOREIGN KEY (financiamiento_id) REFERENCES pos_financiamientos(id) ON DELETE RESTRICT;
alter table public.pos_credito_eventos add constraint pos_credito_eventos_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES pos_ventas(id) ON DELETE RESTRICT;
alter table public.pos_devolucion_items add constraint pos_devolucion_items_devolucion_id_fkey FOREIGN KEY (devolucion_id) REFERENCES pos_devoluciones(id) ON DELETE CASCADE;
alter table public.pos_documento_eventos add constraint pos_documento_eventos_documento_id_fkey FOREIGN KEY (documento_id) REFERENCES pos_documentos(id) ON DELETE CASCADE;
alter table public.pos_documentos add constraint pos_documentos_documento_padre_id_fkey FOREIGN KEY (documento_padre_id) REFERENCES pos_documentos(id);
alter table public.pos_fin_cuotas add constraint pos_fin_cuotas_financiamiento_org_fkey FOREIGN KEY (organizacion_id, financiamiento_id) REFERENCES pos_financiamientos(organizacion_id, id) ON DELETE RESTRICT;
alter table public.pos_fin_pagos add constraint pos_fin_pagos_cuenta_bancaria_id_fkey FOREIGN KEY (cuenta_bancaria_id) REFERENCES pos_cuentas_bancarias(id) ON DELETE RESTRICT;
alter table public.pos_fin_pagos add constraint pos_fin_pagos_cuota_org_fkey FOREIGN KEY (organizacion_id, cuota_id) REFERENCES pos_fin_cuotas(organizacion_id, id) ON DELETE RESTRICT;
alter table public.pos_fin_pagos add constraint pos_fin_pagos_financiamiento_org_fkey FOREIGN KEY (organizacion_id, financiamiento_id) REFERENCES pos_financiamientos(organizacion_id, id) ON DELETE RESTRICT;
alter table public.pos_fin_pagos add constraint pos_fin_pagos_reversa_fkey FOREIGN KEY (reversa_de_id) REFERENCES pos_fin_pagos(id) ON DELETE RESTRICT;
alter table public.pos_financiamientos add constraint pos_financiamientos_refinanciado_a_id_fkey FOREIGN KEY (refinanciado_a_id) REFERENCES pos_financiamientos(id) ON DELETE RESTRICT;
alter table public.pos_financiamientos add constraint pos_financiamientos_refinanciado_desde_id_fkey FOREIGN KEY (refinanciado_desde_id) REFERENCES pos_financiamientos(id) ON DELETE RESTRICT;
alter table public.pos_productos add constraint pos_productos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES pos_categorias(id) ON DELETE SET NULL;
alter table public.pos_productos add constraint pos_productos_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_productos add constraint pos_productos_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES pos_proveedores(id);
alter table public.pos_proveedores add constraint pos_proveedores_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_reparacion_piezas add constraint pos_reparacion_piezas_almacen_id_fkey FOREIGN KEY (almacen_id) REFERENCES pos_almacenes(id) ON DELETE RESTRICT;
alter table public.pos_reparacion_piezas add constraint pos_reparacion_piezas_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES pos_productos(id) ON DELETE RESTRICT;
alter table public.pos_reparacion_piezas add constraint pos_reparacion_piezas_reparacion_id_fkey FOREIGN KEY (reparacion_id) REFERENCES pos_reparaciones(id) ON DELETE RESTRICT;
alter table public.pos_reparaciones add constraint pos_reparaciones_garantia_origen_id_fkey FOREIGN KEY (garantia_origen_id) REFERENCES pos_reparaciones(id) ON DELETE RESTRICT;
alter table public.pos_transferencia_item_seriales add constraint pos_transferencia_item_seriales_serial_id_fkey FOREIGN KEY (serial_id) REFERENCES pos_seriales(id) ON DELETE RESTRICT;
alter table public.pos_transferencia_item_seriales add constraint pos_transferencia_item_seriales_transferencia_item_id_fkey FOREIGN KEY (transferencia_item_id) REFERENCES pos_transferencia_items(id) ON DELETE RESTRICT;
alter table public.pos_transferencia_items add constraint pos_transferencia_items_transferencia_id_fkey FOREIGN KEY (transferencia_id) REFERENCES pos_transferencias(id) ON DELETE CASCADE;
alter table public.pos_venta_items add constraint pos_venta_items_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.pos_venta_items add constraint pos_venta_items_venta_id_fkey FOREIGN KEY (venta_id) REFERENCES pos_ventas(id) ON DELETE CASCADE;
alter table public.pos_ventas add constraint pos_ventas_caja_id_fkey FOREIGN KEY (caja_id) REFERENCES pos_cajas(id) ON DELETE SET NULL;
alter table public.pos_ventas add constraint pos_ventas_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES pos_clientes(id) ON DELETE SET NULL;
alter table public.pos_ventas add constraint pos_ventas_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_usuario_sistema_id_fkey FOREIGN KEY (usuario_sistema_id) REFERENCES usuarios_sistema(id);
alter table public.rrhh_nomina_lineas add constraint rrhh_nomina_lineas_nomina_id_fkey FOREIGN KEY (nomina_id) REFERENCES rrhh_nominas(id) ON DELETE CASCADE;
alter table public.saas_pagos add constraint saas_pagos_suscripcion_id_fkey FOREIGN KEY (suscripcion_id) REFERENCES saas_suscripciones(id) ON DELETE CASCADE;
alter table public.usuario_preferencias add constraint usuario_preferencias_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES usuarios_sistema(id) ON DELETE CASCADE;
alter table public.usuarios_sistema add constraint usuarios_sistema_organizacion_id_fkey FOREIGN KEY (organizacion_id) REFERENCES organizaciones(id);

-- ---------------------------------------------------------------- Índices (no respaldan constraints)
CREATE INDEX auditoria_cliente_id_idx ON public.auditoria USING btree (cliente_id);
CREATE INDEX auditoria_organizacion_id_idx ON public.auditoria USING btree (organizacion_id);
CREATE INDEX pos_abonos_cli_idx ON public.pos_abonos USING btree (cliente_id);
CREATE INDEX idx_pos_acceso_org ON public.pos_acceso USING btree (organizacion_id);
CREATE INDEX idx_pos_alm_org ON public.pos_almacenes USING btree (organizacion_id);
CREATE INDEX pos_apartados_cliente_idx ON public.pos_apartados USING btree (organizacion_id, cliente_id, estado);
CREATE UNIQUE INDEX pos_apartados_serial_activo_uidx ON public.pos_apartados USING btree (organizacion_id, serial_id) WHERE ((serial_id IS NOT NULL) AND (estado <> ALL (ARRAY['cancelado'::text, 'entregado'::text, 'vencido'::text])));
CREATE INDEX idx_pos_aslin_asiento ON public.pos_asiento_lineas USING btree (asiento_id);
CREATE INDEX idx_pos_asientos_org ON public.pos_asientos USING btree (organizacion_id);
CREATE UNIQUE INDEX pos_asientos_fin_pago_origen_uidx ON public.pos_asientos USING btree (organizacion_id, tipo, origen_id) WHERE ((origen_id IS NOT NULL) AND (tipo = ANY (ARRAY['pago_cuota'::text, 'reversa_pago_cuota'::text])));
CREATE UNIQUE INDEX pos_asientos_pos_origen_uidx ON public.pos_asientos USING btree (organizacion_id, tipo, origen_id) WHERE ((origen_id IS NOT NULL) AND (tipo = ANY (ARRAY['venta'::text, 'compra'::text])));
CREATE UNIQUE INDEX pos_banco_conc_ext_uidx ON public.pos_banco_conciliaciones USING btree (extracto_id);
CREATE UNIQUE INDEX pos_banco_conc_mov_uidx ON public.pos_banco_conciliaciones USING btree (movimiento_id);
CREATE INDEX pos_banco_conc_org_idx ON public.pos_banco_conciliaciones USING btree (organizacion_id, cuenta_bancaria_id);
CREATE UNIQUE INDEX pos_banco_extracto_fp_uidx ON public.pos_banco_extractos USING btree (organizacion_id, cuenta_bancaria_id, fingerprint);
CREATE INDEX pos_banco_extracto_org_fecha_idx ON public.pos_banco_extractos USING btree (organizacion_id, cuenta_bancaria_id, fecha DESC);
CREATE INDEX pos_banco_mov_org_fecha_idx ON public.pos_banco_movimientos USING btree (organizacion_id, cuenta_bancaria_id, fecha DESC);
CREATE UNIQUE INDEX pos_banco_mov_origen_clave_uidx ON public.pos_banco_movimientos USING btree (organizacion_id, origen_clave) WHERE (origen_clave IS NOT NULL);
CREATE INDEX pos_caja_mov_idx ON public.pos_caja_movimientos USING btree (caja_id);
CREATE UNIQUE INDEX pos_cajas_una_abierta_por_usuario_uidx ON public.pos_cajas USING btree (organizacion_id, usuario_id) WHERE ((estado = 'abierta'::text) AND (usuario_id IS NOT NULL));
CREATE INDEX pos_cajas_usuario_fecha_idx ON public.pos_cajas USING btree (organizacion_id, usuario_id, apertura DESC);
CREATE INDEX pos_compra_items_idx ON public.pos_compra_items USING btree (compra_id);
CREATE INDEX pos_compra_pagos_prov_idx ON public.pos_compra_pagos USING btree (proveedor_id);
CREATE UNIQUE INDEX pos_compras_org_operacion_uidx ON public.pos_compras USING btree (organizacion_id, operacion_id) WHERE (operacion_id IS NOT NULL);
CREATE INDEX pos_compras_prov_idx ON public.pos_compras USING btree (proveedor_id);
CREATE INDEX idx_pos_cotiz_items_cot ON public.pos_cotizacion_items USING btree (cotizacion_id);
CREATE INDEX idx_pos_cotiz_org ON public.pos_cotizaciones USING btree (organizacion_id);
CREATE INDEX pos_credito_eventos_fin_idx ON public.pos_credito_eventos USING btree (financiamiento_id, created_at DESC);
CREATE INDEX pos_credito_eventos_org_idx ON public.pos_credito_eventos USING btree (organizacion_id, created_at DESC);
CREATE INDEX pos_credito_eventos_venta_idx ON public.pos_credito_eventos USING btree (venta_id, created_at DESC);
CREATE INDEX idx_pos_crm_org ON public.pos_crm USING btree (organizacion_id);
CREATE INDEX idx_pos_cuentas_org ON public.pos_cuentas USING btree (organizacion_id);
CREATE UNIQUE INDEX pos_cuentas_org_codigo_uidx ON public.pos_cuentas USING btree (organizacion_id, codigo);
CREATE UNIQUE INDEX pos_cuentas_bancarias_default_uidx ON public.pos_cuentas_bancarias USING btree (organizacion_id) WHERE ((predeterminada IS TRUE) AND (activa IS TRUE));
CREATE UNIQUE INDEX pos_cuentas_bancarias_numero_uidx ON public.pos_cuentas_bancarias USING btree (organizacion_id, regexp_replace(lower(numero), '[^0-9a-z]'::text, ''::text, 'g'::text));
CREATE INDEX pos_cuentas_bancarias_org_idx ON public.pos_cuentas_bancarias USING btree (organizacion_id, activa);
CREATE INDEX idx_pos_dev_items_dev ON public.pos_devolucion_items USING btree (devolucion_id);
CREATE INDEX idx_pos_dev_org ON public.pos_devoluciones USING btree (organizacion_id);
CREATE INDEX idx_pos_documento_eventos_doc ON public.pos_documento_eventos USING btree (documento_id);
CREATE INDEX idx_pos_documentos_org ON public.pos_documentos USING btree (organizacion_id);
CREATE INDEX idx_pos_documentos_origen ON public.pos_documentos USING btree (tabla_origen, registro_id);
CREATE INDEX idx_pos_documentos_padre ON public.pos_documentos USING btree (documento_padre_id);
CREATE INDEX idx_pos_fincuo_fin ON public.pos_fin_cuotas USING btree (financiamiento_id);
CREATE INDEX idx_pos_fincuo_venc ON public.pos_fin_cuotas USING btree (fecha_venc);
CREATE UNIQUE INDEX pos_fin_cuota_numero_uidx ON public.pos_fin_cuotas USING btree (organizacion_id, financiamiento_id, numero);
CREATE UNIQUE INDEX pos_fin_pagos_operacion_uidx ON public.pos_fin_pagos USING btree (organizacion_id, operacion_id) WHERE (operacion_id IS NOT NULL);
CREATE UNIQUE INDEX pos_fin_reversa_unica_uidx ON public.pos_fin_pagos USING btree (organizacion_id, reversa_de_id) WHERE ((tipo = 'reversa'::text) AND (reversa_de_id IS NOT NULL));
CREATE UNIQUE INDEX pos_fin_refinanciado_a_uidx ON public.pos_financiamientos USING btree (refinanciado_a_id) WHERE (refinanciado_a_id IS NOT NULL);
CREATE UNIQUE INDEX pos_financiamiento_venta_uidx ON public.pos_financiamientos USING btree (organizacion_id, venta_id) WHERE (venta_id IS NOT NULL);
CREATE INDEX idx_pos_invmov_org ON public.pos_inv_movimientos USING btree (organizacion_id);
CREATE INDEX idx_pos_invmov_prod ON public.pos_inv_movimientos USING btree (producto_id);
CREATE INDEX idx_pos_ncf_org ON public.pos_ncf_secuencias USING btree (organizacion_id);
CREATE INDEX pos_productos_cat_idx ON public.pos_productos USING btree (categoria_id);
CREATE INDEX pos_rep_piezas_prod_idx ON public.pos_reparacion_piezas USING btree (organizacion_id, producto_id, almacen_id, estado);
CREATE INDEX pos_rep_piezas_rep_idx ON public.pos_reparacion_piezas USING btree (organizacion_id, reparacion_id, estado);
CREATE INDEX idx_pos_rep_estado ON public.pos_reparaciones USING btree (estado);
CREATE UNIQUE INDEX pos_rep_garantia_activa_uidx ON public.pos_reparaciones USING btree (organizacion_id, garantia_origen_id) WHERE ((garantia_origen_id IS NOT NULL) AND (lower(COALESCE(estado, ''::text)) <> ALL (ARRAY['entregado'::text, 'cancelado'::text])));
CREATE INDEX idx_pos_sec_org ON public.pos_secuencias USING btree (organizacion_id);
CREATE INDEX idx_pos_seriales_org ON public.pos_seriales USING btree (organizacion_id);
CREATE INDEX idx_pos_seriales_prod ON public.pos_seriales USING btree (producto_id);
CREATE UNIQUE INDEX pos_seriales_serial_unico_org ON public.pos_seriales USING btree (organizacion_id, serial);
CREATE INDEX idx_pos_stkalm_org ON public.pos_stock_almacen USING btree (organizacion_id);
CREATE INDEX idx_pos_stkalm_prod ON public.pos_stock_almacen USING btree (producto_id);
CREATE INDEX idx_pos_transf_item_seriales_item ON public.pos_transferencia_item_seriales USING btree (transferencia_item_id);
CREATE INDEX idx_pos_transf_item_seriales_org ON public.pos_transferencia_item_seriales USING btree (organizacion_id);
CREATE INDEX idx_pos_transf_item_seriales_serial ON public.pos_transferencia_item_seriales USING btree (serial_id);
CREATE INDEX idx_pos_transf_items ON public.pos_transferencia_items USING btree (transferencia_id);
CREATE INDEX idx_pos_transf_org ON public.pos_transferencias USING btree (organizacion_id);
CREATE INDEX idx_pos_vendedores_org ON public.pos_vendedores USING btree (organizacion_id);
CREATE INDEX pos_venta_items_vid_idx ON public.pos_venta_items USING btree (venta_id);
CREATE INDEX pos_ventas_cli_idx ON public.pos_ventas USING btree (cliente_id);
CREATE UNIQUE INDEX pos_ventas_ncf_unico_por_org ON public.pos_ventas USING btree (organizacion_id, ncf) WHERE ((ncf IS NOT NULL) AND (ncf <> ''::text));
CREATE UNIQUE INDEX pos_ventas_org_operacion_uidx ON public.pos_ventas USING btree (organizacion_id, operacion_id) WHERE (operacion_id IS NOT NULL);
CREATE INDEX pos_venta_susp_org_idx ON public.pos_ventas_suspendidas USING btree (organizacion_id);
CREATE INDEX idx_rrhh_empleados_org ON public.rrhh_empleados USING btree (organizacion_id);
CREATE INDEX idx_rrhh_nlin_nomina ON public.rrhh_nomina_lineas USING btree (nomina_id);
CREATE INDEX idx_rrhh_nominas_org ON public.rrhh_nominas USING btree (organizacion_id);
CREATE INDEX idx_saas_pagos_sus ON public.saas_pagos USING btree (suscripcion_id);
