-- STUDIO — 07 triggers
-- 72 triggers no internos (pg_trigger, tgisinternal = false) sobre las tablas del set.
-- Requiere que 06_funciones.sql ya se haya ejecutado (incluye set_organizacion_id, nx_*, set_auditoria_metadata y pos_*).

CREATE TRIGGER trg_auditoria_metadata BEFORE INSERT ON public.auditoria FOR EACH ROW EXECUTE FUNCTION set_auditoria_metadata();
CREATE TRIGGER trg_nx_capturar_excepcion_operativa AFTER INSERT ON public.auditoria FOR EACH ROW EXECUTE FUNCTION nx_capturar_excepcion_operativa();
CREATE TRIGGER trg_nx_validar_caja_abono BEFORE INSERT OR UPDATE ON public.pos_abonos FOR EACH ROW EXECUTE FUNCTION nx_validar_caja_propietario();
CREATE TRIGGER trg_org_pos_abonos BEFORE INSERT ON public.pos_abonos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_acceso BEFORE INSERT ON public.pos_acceso FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_alm BEFORE INSERT ON public.pos_almacenes FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_apap_org BEFORE INSERT ON public.pos_apartado_pagos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_apa_org BEFORE INSERT ON public.pos_apartados FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_asiento_lineas_periodo_guard BEFORE INSERT OR DELETE OR UPDATE ON public.pos_asiento_lineas FOR EACH ROW EXECUTE FUNCTION pos_guard_periodo_asiento();
CREATE TRIGGER trg_org_pos_aslin BEFORE INSERT ON public.pos_asiento_lineas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_asientos_periodo_guard BEFORE INSERT OR DELETE OR UPDATE ON public.pos_asientos FOR EACH ROW EXECUTE FUNCTION pos_guard_periodo_asiento();
CREATE TRIGGER trg_org_pos_asientos BEFORE INSERT ON public.pos_asientos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_nx_validar_caja_movimiento BEFORE INSERT OR UPDATE ON public.pos_caja_movimientos FOR EACH ROW EXECUTE FUNCTION nx_validar_caja_propietario();
CREATE TRIGGER trg_org_pos_caja_movimientos BEFORE INSERT ON public.pos_caja_movimientos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_nx_caja_asignar_propietario BEFORE INSERT ON public.pos_cajas FOR EACH ROW EXECUTE FUNCTION nx_caja_asignar_propietario();
CREATE TRIGGER trg_nx_caja_proteger_actualizacion BEFORE UPDATE ON public.pos_cajas FOR EACH ROW EXECUTE FUNCTION nx_caja_proteger_actualizacion();
CREATE TRIGGER trg_org_pos_cajas BEFORE INSERT ON public.pos_cajas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_categorias BEFORE INSERT ON public.pos_categorias FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_clientes BEFORE INSERT ON public.pos_clientes FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE CONSTRAINT TRIGGER pos_compra_items_recontabilizar AFTER INSERT OR DELETE OR UPDATE ON public.pos_compra_items DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION pos_trg_recontabilizar_compra_item();
CREATE TRIGGER trg_org_pos_compra_items BEFORE INSERT ON public.pos_compra_items FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_compra_pagos BEFORE INSERT ON public.pos_compra_pagos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_compras_recontabilizar AFTER UPDATE ON public.pos_compras FOR EACH ROW EXECUTE FUNCTION pos_trg_recontabilizar_compra_cabecera();
CREATE TRIGGER trg_org_pos_compras BEFORE INSERT ON public.pos_compras FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_config BEFORE INSERT ON public.pos_config FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_cotiz_items BEFORE INSERT ON public.pos_cotizacion_items FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_cotiz BEFORE INSERT ON public.pos_cotizaciones FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_crm BEFORE INSERT ON public.pos_crm FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_cuentas BEFORE INSERT ON public.pos_cuentas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_dev_items BEFORE INSERT ON public.pos_devolucion_items FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_dev BEFORE INSERT ON public.pos_devoluciones FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_documento_eventos BEFORE INSERT ON public.pos_documento_eventos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_documentos BEFORE INSERT ON public.pos_documentos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_fin_cuotas_org_inmutable BEFORE UPDATE ON public.pos_fin_cuotas FOR EACH ROW EXECUTE FUNCTION nx_impedir_cambio_organizacion();
CREATE TRIGGER pos_fincuo_org BEFORE INSERT ON public.pos_fin_cuotas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_fin_pago_inmutable BEFORE DELETE OR UPDATE ON public.pos_fin_pagos FOR EACH ROW EXECUTE FUNCTION pos_fin_bloquear_mutacion_pago();
CREATE TRIGGER pos_fin_pago_recalcular AFTER INSERT ON public.pos_fin_pagos FOR EACH ROW EXECUTE FUNCTION pos_fin_recalcular_cache();
CREATE TRIGGER pos_fin_pago_validar BEFORE INSERT ON public.pos_fin_pagos FOR EACH ROW EXECUTE FUNCTION pos_fin_validar_pago_insert();
CREATE TRIGGER pos_fin_pagos_org_inmutable BEFORE UPDATE ON public.pos_fin_pagos FOR EACH ROW EXECUTE FUNCTION nx_impedir_cambio_organizacion();
CREATE TRIGGER pos_finpag_org BEFORE INSERT ON public.pos_fin_pagos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_fin_org BEFORE INSERT ON public.pos_financiamientos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_financiamientos_org_inmutable BEFORE UPDATE ON public.pos_financiamientos FOR EACH ROW EXECUTE FUNCTION nx_impedir_cambio_organizacion();
CREATE TRIGGER trg_org_pos_invmov BEFORE INSERT ON public.pos_inv_movimientos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_ncf BEFORE INSERT ON public.pos_ncf_secuencias FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_niveles_precio BEFORE INSERT ON public.pos_niveles_precio FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_pref_org BEFORE INSERT ON public.pos_prefacturas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_producto_niveles BEFORE INSERT ON public.pos_producto_niveles FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_productos BEFORE INSERT ON public.pos_productos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_proveedores BEFORE INSERT ON public.pos_proveedores FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_rep_guard_cobro_garantia BEFORE INSERT OR UPDATE OF cobrado, cobrado_monto, garantia_cobro_autorizado ON public.pos_reparaciones FOR EACH ROW EXECUTE FUNCTION pos_rep_guard_cobro_garantia();
CREATE TRIGGER pos_rep_org BEFORE INSERT ON public.pos_reparaciones FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_sec BEFORE INSERT ON public.pos_secuencias FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_seriales BEFORE INSERT ON public.pos_seriales FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_stkalm BEFORE INSERT ON public.pos_stock_almacen FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_transf_item_seriales BEFORE INSERT ON public.pos_transferencia_item_seriales FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_transf_items BEFORE INSERT ON public.pos_transferencia_items FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_transf BEFORE INSERT ON public.pos_transferencias FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_pos_vendedores BEFORE INSERT ON public.pos_vendedores FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_venta_guard_stock_reservado_taller BEFORE INSERT OR UPDATE OF producto_id, cantidad ON public.pos_venta_items FOR EACH ROW EXECUTE FUNCTION pos_rep_guard_stock_reservado_venta();
CREATE TRIGGER pos_venta_item_snapshot_costo BEFORE INSERT OR UPDATE OF producto_id ON public.pos_venta_items FOR EACH ROW EXECUTE FUNCTION pos_snapshot_costo_venta_item();
CREATE CONSTRAINT TRIGGER pos_venta_items_recontabilizar AFTER INSERT OR DELETE OR UPDATE ON public.pos_venta_items DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION pos_trg_recontabilizar_venta_item();
CREATE TRIGGER trg_org_pos_venta_items BEFORE INSERT ON public.pos_venta_items FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER pos_ventas_recontabilizar AFTER UPDATE ON public.pos_ventas FOR EACH ROW EXECUTE FUNCTION pos_trg_recontabilizar_venta_cabecera();
CREATE TRIGGER trg_nx_validar_caja_venta BEFORE INSERT OR UPDATE ON public.pos_ventas FOR EACH ROW EXECUTE FUNCTION nx_validar_caja_propietario();
CREATE TRIGGER trg_org_pos_ventas BEFORE INSERT ON public.pos_ventas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_pos_validar_venta_con_almacen BEFORE INSERT OR UPDATE OF almacen_id, estado ON public.pos_ventas FOR EACH ROW EXECUTE FUNCTION pos_validar_venta_con_almacen();
CREATE TRIGGER pos_venta_susp_org BEFORE INSERT ON public.pos_ventas_suspendidas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_rrhh_empleados BEFORE INSERT ON public.rrhh_empleados FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_rrhh_nlin BEFORE INSERT ON public.rrhh_nomina_lineas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER trg_org_rrhh_nominas BEFORE INSERT ON public.rrhh_nominas FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER saas_pagos_org BEFORE INSERT ON public.saas_pagos FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
CREATE TRIGGER saas_sus_org BEFORE INSERT ON public.saas_suscripciones FOR EACH ROW EXECUTE FUNCTION set_organizacion_id();
